/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddLinkModal: typeof import('./components/dashboard/AddLinkModal.vue')['default']
    Empty: typeof import('./components/Empty.vue')['default']
    IconDropdown: typeof import('./components/dashboard/IconDropdown.vue')['default']
    ProfileForm: typeof import('./components/user/ProfileForm.vue')['default']
    QRScanModal: typeof import('./components/dashboard/QRScanModal.vue')['default']
    QuickLinks: typeof import('./components/dashboard/QuickLinks.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUpSignIn: typeof import('./components/auth/SignUpSignIn.vue')['default']
  }
}
