/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddLinkModal: typeof import('./components/dashboard/AddLinkModal.vue')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogOverlay: typeof import('@headlessui/vue')['DialogOverlay']
    DialogTitle: typeof import('@headlessui/vue')['DialogTitle']
    Empty: typeof import('./components/Empty.vue')['default']
    IconDropdown: typeof import('./components/dashboard/IconDropdown.vue')['default']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    ProfileForm: typeof import('./components/user/ProfileForm.vue')['default']
    QRScanModal: typeof import('./components/dashboard/QRScanModal.vue')['default']
    QuickLinks: typeof import('./components/dashboard/QuickLinks.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUpSignIn: typeof import('./components/auth/SignUpSignIn.vue')['default']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
  }
}
